version: "2.4"


volumes:
  mysql:


services:

  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ../:/www
      - ./nginx:/etc/nginx/conf.d

  php-fpm:
    build: ./php-fpm
    volumes:
      - ../:/www
  
  phpstorm-php:
    build: ./php-fpm
    volumes:
      - ../:/www

  mysql:
    image: mysql:latest
    ports:
    - "3306:3306"
    volumes:
    - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    environment:
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root

  redis:
    image: redis:latest
    ports:
    - "6379:6379"